server:
  port: 9998

spring:
  # 外面登录
  security:
    user:
      name: admin
      password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
management.endpoint.bus-refresh.enabled: true
management.endpoints.web.exposure.include: bus-refresh

eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
  instance:
  # 方式二、使用Eureka提交凭据
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}